### ISSUE TITLE
Highlighting on array when stepping backwards during Find operation

### ISSUE THREAD

**Issue by d4vidsha** [d4vidsha/algorithms-in-action.github.io#50]
Highlighting issues when stepping backwards during Find operation in Union-Find.

Steps to reproduce:
1. Run union through first, then run find through
2. Then, when you step back to the beginning, it looks like the below which is wrong. At the beginning only 2 should be highlighted.
![image](https://github.com/d4vidsha/algorithms-in-action.github.io/assets/70577814/aa7afe8b-dea5-4ef3-a70b-e62b9983f7da)

**Comment by cate-21** [comment]
Resolved by creating a fresh array instance rather than using the old visualiser.
